### PR TITLE
fix crash with animated nodes (inventorycube related)

### PR DESCRIPTION
**Pull request by Niklp09**
`tile_to_image` function by HybridDog (LGPLv2.1+)

Fix for https://github.com/minetest-mods/drawers/issues/76 @lnjX

### CODE REVIEW

**Comment by lnjX** [comment]
We need to ask HybridDog for permission to use under MIT or relicense the mod to LGPL-2.1-or-later (which should be possible because MIT is LGPL compatible I think). And HybridDog needs to be credited in a copyright line (or a [REUSE](https://reuse.software/spec/) `# SPDX-FileCopyrightText:` line).

**Comment by Niklp09** [comment]
@HybridDog

**Comment by SmallJoker** [comment]
Is this a general issue with `core.inventorycube` (i.e. flawed function)? If so, please open an issue on minetest/minetest so that it can be fixed.

**Comment by lnjX** [comment]
@SmallJoker The code expected that `tiles` is always a list of strings (which it isn't always). `core.inventorycube()` work fine. :)

**Comment by HybridDog** [comment]
Yes, you can use my code under MIT. And it's also fine for me if you don't credit me for this function.

**Pull request merged**
