### PR TITLE
better inventory view in drawer formspec

### PR DESCRIPTION
**Pull request by Niklp09**
previously:
grafik

after:
grafik

### CODE REVIEW

**Comment by SmallJoker** [comment]
The previous layout mimics the Minetest Game chest which makes it at least a bit consistent when used with that game.

**Comment by Niklp09** [comment]
done
grafik

**Review by SmallJoker — APPROVED** [review]
LGTM; Will merge in a few days unless there's objections.

**Comment by OgelGames** [comment]
This breaks Mineclone2 support, because it has a 9x4 inventory. There should be a check (for `mcl_core`) to decide whether to use 8x4 or 9x4.

**Pull request merged**
