### PR TITLE
Open and close sound, two variations

### PR DESCRIPTION
**Pull request by tacotexmex**
Now they just need code to play. I imagine a high gain will be annoying after a while, so consider a subtle gain. Happy sunday!

### CODE REVIEW

**Comment by LNJ2** [comment]
I'm unsure if it's ok to use CC BY-NC media ...
I'd like to avoid this. I'm also not sure if this is allowed in the Minetest Forums and in the Minetest Mods Organisation, because the NC makes it an non-free license (correct me if I'm wrong).

**Comment by tacotexmex** [comment]
Oh okay, I'll look into an alternative.

**Comment by tacotexmex** [comment]
There's another NC here https://github.com/minetest-mods/sounding_line/blob/23c082f7c38c224ce8e2a0f6c538cd813a8d192a/sounds/license.txt
I'm afraid I added that one too… 😊

**Comment by tacotexmex** [comment]
Better? 😁

**Comment by LNJ2** [comment]
@tacotexmex Yes, that's better. I'll merge it when the functionality for that is implemented.

**Comment by tacotexmex** [comment]
Beautiful. I might modify sounds again depending on how the feel in-game, but that's a later issue.

**Comment by LNJ2** [comment]
But one thing: Drawers can't be opened/closed, you can only add and remove things. You should better rename the sounds.

**Comment by tacotexmex** [comment]
I know they don't open or close visually but I figured that 
- only opening sound
- only closing sound
are both misleading since all actions (deposit, withdraw) contains both those movements (only not visually). Hence the naming. I can call them `drawers_interact.x.ogg` if you prefer.

**Comment by LNJ2** [comment]
I just merged it into a new develop branch, there I'll now do the "back-end" for your feature. Thank you! :smiley:

**Comment by tacotexmex** [comment]
No, thank _you_! 😁

**Comment by LNJ2** [comment]
@tacotexmex Well, in the end it's my mod and you helped me to improve it!
I tested the sounds (it's working now on develop): they seem a bit too long, but for now it's ok.

**Comment by tacotexmex** [comment]
Exactly, thank you for making a drawer mod for me to add sound to.

I'll do a test run to get a feel for it in-game.

**Comment by tacotexmex** [comment]
I agree, they feel a bit long. Perhaps the first or second part of the sound should be cut out, or made into two new variations. I'll prod it a bit an see what comes out but yes, it's good enough for the time being.

**Pull request merged**
